### ISSUE TITLE
插件无法正常工作，Mirai Core2 .9 

### ISSUE THREAD

**Issue by greenhandzdl** [Raptor-wxw/HiveSearchForQQ#1]
![Screenshot_20220209_174454_io github mzdluo123 mirai android](https://user-images.githubusercontent.com/61241103/153170663-c91406f1-1fdf-4236-be60-297c121d7a7c.jpg)
![Screenshot_20220209_174500_io github mzdluo123 mirai android](https://user-images.githubusercontent.com/61241103/153170720-380b1fe1-78c9-40b8-8ff4-bfffb7d76d86.jpg)
![Screenshot_20220209_174505_io github mzdluo123 mirai android](https://user-images.githubusercontent.com/61241103/153170778-d899b48e-1a24-4596-93e6-a2eaead1d49a.jpg)

**Comment by ThinkerWen** [comment]
现在好了，接口挂了忘了维护，多谢提醒

**Comment by Master-Panda** [comment]
怎么用呢大大（）

**Comment by Raptor-wxw** [comment]
很遗憾，你来晚了，接口挂了，我没时间维护了

**Comment by ThinkerWen** [comment]
> 

下载最新版的release插件，放到plugin文件夹下就可以了，和别的插件使用方式相同

**Comment by ThinkerWen** [comment]
插件已修复，新版本已发布
